# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d69d9862a3a55c943fc62494e54eedd793e9f4f7abe2db7398fec8e9d0a9d6a0640c9387de8a9590a56cbfc3ce78ac1e0ea74060435497f3d9c6ce48468eaaf

test:
  secret_key_base: f8a9d805a24013df6a5fe04d9a019cf1e77c7fdaba966e5caeb31d85a7dc1dcf45157628d5de934b1db80f00fcffb73202142e1530d1e032fa21439bd33ea32d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
